


logging:
  level:
    com:
      book:
        demo: INFO
    org:
      springframework:
        messaging: DEBUG

#
#spring:
#  task:
#    execution:
#      pool:
#        core-size: 8
#        max-size: 8



webclient.h2-console-port: 8081

#spring:
#  datasource:
#    username: sa
#    password:
