


logging:
  level:
    com:
      book:
        demo: info
    org:
      springframework: debug

myapplication:
  datasource:
    dbdriver: "com.mysql.cj.jdbc.Driver"
    dburl: "jdbc:mysql://localhost:3306/counts?serverTimezone=Asia/Seoul&useSSL=false"
    dbUser: "root"
    dbpasswd: "1234qwer"

spring:
  profiles:
    active: local
#  datasource:
#    url: jdbc:mysql://localhost:3306/world?serverTimeZone=UTC&CharacterEncoding=UTF-8
#    username: root
#    password: 1234qwer
#    hikari:
#      maximum-pool-size: 10
#      connection-timeout: 5000
#      connection-init-sql: SELECT 1
#      validation-timeout: 2000
#      minimum-idle: 10
#      idle-timeout: 600000
#      max-lifetime: 1800000

server:
  port: 8080